export type LogSeverity = 'INFO' | 'WARNING' | 'ERROR'

export enum LogEvent {
  FORM_SUBMITTING = 'FORM_SUBMITTING',
  FORM_SUBMITTED = 'FORM_SUBMITTED',
  FORM_SUBMISSION_FAILED = 'FORM_SUBMISSION_FAILED',
  FORM_LOADING = 'FORM_LOADING',
  FORM_FETCH_FAILED = 'FORM_FETCH_FAILED',
  FORM_RULE_EVALUATION_FAILED = 'FORM_RULE_EVALUATION_FAILED',

  SESSION_ONGOING = 'SESSION_ONGOING',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_COMPLETED = 'SESSION_COMPLETED',

  MESSAGE_MARKING_AS_READ = 'MESSAGE_MARKING_AS_READ',
  MESSAGE_MARKED_AS_READ = 'MESSAGE_MARKED_AS_READ',
  MESSAGE_MARKING_AS_READ_FAILED = 'MESSAGE_MARKING_AS_READ_FAILED',

  CHECKLIST_SUBMITTING = 'CHECKLIST_SUBMITTING',
  CHECKLIST_SUBMITTED = 'CHECKLIST_SUBMITTED',
  CHECKLIST_SUBMITTING_FAILED = 'CHECKLIST_SUBMITTING_FAILED',

  ACTIVITIES_FETCH_FAILED = 'ACTIVITIES_FETCH_FAILED',
  ACTIVITIES_LIST_CHANGED = 'ACTIVITIES_LIST_CHANGED',
  ACTIVITY_LOADING = 'ACTIVITY_LOADING',
  ACTIVITY_CHANGED = 'ACTIVITY_CHANGED',
  ACTIVITY_NO_ACTIVE_FOUND = 'ACTIVITY_NO_ACTIVE_FOUND',

  ACTIVITIES_START_POLLING = 'ACTIVITIES_START_POLLING',
  ACTIVITIES_STOP_POLLING = 'ACTIVITIES_STOP_POLLING',

  SUBSCRIPTION_ACTIVITY_CREATED = 'SUBSCRIPTION_ACTIVITY_CREATED',
  SUBSCRIPTION_ACTIVITY_COMPLETED = 'SUBSCRIPTION_ACTIVITY_COMPLETED',
  SUBSCRIPTION_ACTIVITY_EXPIRED = 'SUBSCRIPTION_ACTIVITY_EXPIRED',
  SUBSCRIPTION_ACTIVITY_DUPLICATE = 'SUBSCRIPTION_ACTIVITY_DUPLICATE',

  GRAPHQL_WS_CONNECTED = 'GRAPHQL_WS_CONNECTED',
  GRAPHQL_WS_ERROR = 'GRAPHQL_WS_ERROR',
  GRAPHQL_WS_DISCONNECTED = 'GRAPHQL_WS_DISCONNECTED',

  REMOTE_SINGLE_SELECT_OPTIONS = 'REMOTE_SINGLE_SELECT_OPTIONS',

  SOL_API_REQUEST = 'SOL_API_REQUEST',
}
