name: Production Deployment 

on:
  push:
    tags:
    - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Production release message
        run: |
          echo $RELEASE_VERSION
          echo "Releasing version ${{ env.RELEASE_VERSION }} to PRODUCTION"
          
  merge-main-to-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Git config
      run: |
          git config --local user.email "mohsinhayat104@gmail.com" # for testing only, we can use any email that has permissions on this repo
          git config --local user.name "mohsinht" # for testing only, we can use any username that has permissions on this repo
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Production release message
      run: |
        echo $RELEASE_VERSION
        echo "Releasing version ${{ env.RELEASE_VERSION }} to PRODUCTION"
    - name: Merge main into production
      run: |
        git fetch --unshallow
        git checkout production
        git pull origin production
        git merge --no-ff origin/main -m "Merging main into production – ${{ env.RELEASE_VERSION }}"
        git push origin production
