name: 🚨 Production Deployment

on:
  workflow_dispatch:
    inputs:
      deployment-type:
        description: 'Deploy to production from which branch? (staging for release, main for hotfix)'
        required: true
        default: 'staging'
        type: choice
        options:
          - 'main'
          - 'staging'

jobs:
  merge-release-content-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set Git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Set deployment type
        run: |
          echo "DEPLOYMENT_TYPE=${{ github.event.inputs.deployment-type }}" >> $GITHUB_ENV
        shell: bash
      - name: Merge "${{ env.DEPLOYMENT_TYPE }}" into production
        run: |
          git checkout "${{ env.DEPLOYMENT_TYPE }}"
          git pull origin production
          git merge --no-ff HEAD -m "merge changes into production branch"
          git push origin HEAD:production

  merge-release-content-to-production-us:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set Git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Set deployment type
        run: |
          echo "DEPLOYMENT_TYPE=${{ github.event.inputs.deployment-type }}" >> $GITHUB_ENV
        shell: bash
      - name: Merge "${{ env.DEPLOYMENT_TYPE }}" into production-us
        run: |
          git checkout "${{ env.DEPLOYMENT_TYPE }}"
          git pull origin production-us
          git merge --no-ff HEAD -m "merge changes into production-us branch"
          git push origin HEAD:production-us
