name: Production Deployment 

on:
  workflow_dispatch

jobs:
  merge-release-content-to-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Git config
      run: |
          git config --local user.email "mohsinhayat104@gmail.com" # for testing only, we can use any email that has permissions on this repo
          git config --local user.name "mohsinht" # for testing only, we can use any username that has permissions on this repo
    - name: Merge release content into production
      run: |
        git fetch --unshallow
        git checkout production
        git pull origin production
        git merge --no-ff origin/staging -m "merge staging in production"
        git push origin production
