name: Production Deployment 

on:
  push:
    tags:
    - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Production release message
        run: |
          echo $RELEASE_VERSION
          echo "Releasing version ${{ env.RELEASE_VERSION }} to PRODUCTION"
          
  merge-main-to-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Merge main into production
      run: |
          git fetch --unshallow
          git checkout production
          git pull origin production
          git merge --no-ff origin/main -m "Merging main into production – ${{ env.RELEASE_VERSION }}"
          git push origin production
