name: 📊 Publish release on Echoes

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.publish-release.outputs.deployment_id }}
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install -y libdatetime-perl

      - name: Publish release
        run: ./scripts/publish_release.sh
        env:
          ECHOESHQ_API_KEY_RELEASES: ${{ secrets.ECHOESHQ_API_KEY_RELEASES }}

  fail-release:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install -y libdatetime-perl

      - name: Fail release
        run: ./scripts/fail_release.sh
        env:
          ECHOESHQ_API_KEY_RELEASES: ${{ secrets.ECHOESHQ_API_KEY_RELEASES }}
          ECHOESHQ_DEPLOYMENT_ID: ${{ needs.publish-release.outputs.deployment_id }}