name: 📊 Publish release on Echoes

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install -y libdatetime-perl git jq curl

      - name: Publish release
        run: ./scripts/publish_release.sh
        env:
          PLATFORM_API_KEY: ${{ secrets.PLATFORM_API_KEY }}
          PLATFORM_ENDPOINT: ${{ secrets.PLATFORM_ENDPOINT }}