name: 🚧 Staging Deployment

on:
  release:
    types: [released]

jobs:
  merge-release-content-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
          echo "Releasing version ${{ env.RELEASE_VERSION }} to STAGING"
      - name: Merge release content into staging
        run: |
          git fetch --unshallow
          git checkout staging
          git pull origin staging
          git merge --no-ff tags/${{ env.RELEASE_VERSION }} -m "merge tags/${{ env.RELEASE_VERSION }} in staging"
          git push origin staging
